### ISSUE TITLE
Objective C Compatibility

### ISSUE THREAD

**Issue by Gantaios** [RahulKatariya/RKParallaxEffect#2]
Hi do you same in objective C can you share it

**Comment by rahul0x24** [comment]
I am afraid, i don't have the same in objective-c but i think its possible to use swift code in objective-c projects too.

**Comment by johndpope** [comment]
@objc public class RKParallaxEffect: NSObject 
should do it.

**Comment by rahul0x24** [comment]
@johndpope: Thank you for help.
@Gantaios: Can you confirm if the solution by @johndpope works ?
