### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by zemadara** [RahulKatariya/RKParallaxEffect#6]
did you plan an update to Swift 3?

**Comment by rahul0x24** [comment]
I will do that soon. Working on it on the 'develop' branch.

**Comment by zemadara** [comment]
i have worked on it but i have an issue on 
`adjustParallaxEffectOnTableHeaderViewWithContentOffset(contentOffset: change![NSKeyValueChange]!.CGPointValue)`
<img width="284" alt="capture d ecran 2016-09-29 a 07 34 38" src="https://cloud.githubusercontent.com/assets/14089551/18942181/353ae9bc-8617-11e6-8a17-56f00fabd192.png">

if you want i can send you my work

**Comment by rahul0x24** [comment]
Can you share more info on the issue you are facing.
I am using Xcode 8 and iOS 10 and at this moment the library works just fine at the develop branch.
There are some issues with `pod lib lint` that is blocking the release v2.0.0.

**Comment by zemadara** [comment]
i have downloaded RKParallaxEffect.swift to convert to Swift 3, i have fixed all the issues for compilation, except one and i don't know how to fix this one.

**Comment by rahul0x24** [comment]
You can download the develop branch from here - https://codeload.github.com/RahulKatariya/RKParallaxEffect/zip/develop
It is already converted to swift 3

**Comment by zemadara** [comment]
thanks
