### ISSUE TITLE
Unexpected offset with segue

### ISSUE THREAD

**Issue by zemadara** [RahulKatariya/RKParallaxEffect#8]
Hello,
when i use a segue to go to an other view and i go back to my view, with the ParallaxEffect, the parallaxeffect is not at his original location, it is lower in my view.

I've tried lot of things but nothing solve my problem can you help me?

**Comment by rahul0x24** [comment]
Hi @zemadara, Can you upload a sample project with the bug ? It will help me easily debug it.

**Comment by zemadara** [comment]
i've tried to put the code on viewDidAppear but i've forget just one line, sorry my bad
