### ISSUE TITLE
Offset or effect gone with segue

### ISSUE THREAD

**Issue by zemadara** [RahulKatariya/RKParallaxEffect#9]
Hi,
this post is a merge of 2 posts, i've recently discovered that when we use segue to go to another view and we go back to the previous one, with the parallaxeffect, there are 2 possibilities:

- if `parallaxEffect = RKParallaxEffect(tableView: self.table)` is on the viewDidLoad, the parallax effect works but it's not at the original position

- if `parallaxEffect = RKParallaxEffect(tableView: self.table)` is on the viewDidAppear, the parallaxeffect is gone but the object is at the original position and sometimes a part of the image is hidden

**Comment by rahul0x24** [comment]
My Bad! 
Try this code, it will work. 🍻
```
 override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        if parallaxEffect == nil {
            parallaxEffect = RKParallaxEffect(tableView: tableView)
            parallaxEffect.isParallaxEffectEnabled = true
            parallaxEffect.isFullScreenTapGestureRecognizerEnabled = true
            parallaxEffect.isFullScreenPanGestureRecognizerEnabled = true
        }
    }
```

**Comment by zemadara** [comment]
Work great thank you
